### ISSUE TITLE
Enable AutoWrap for certain file types

### ISSUE THREAD

**Issue by MrLeeh** [randy3k/AutoWrap#11]
Hello,

first of all: Thanks for the Great Plugin. It' s exactly what i was looking for writing Markdown documents with Sublime Text. A feature proposal of mine would be if AutoWrap gets enabled automaticly for certain file types (e.g. Markdown, Text, rst).

Greetings

**Comment by randy3k** [comment]
Sorry for the long delayed reply. To enable AutoWrap, you would need to edit the syntax specific settings.
Check: https://github.com/randy3k/AutoWrap#to-activate-auto-wrap-for-a-specific-syntax-at-start-up
